name: betacraft-build

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          submodules: recursive
    
    - uses: lukka/get-cmake@latest
      
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11.1
      with:
          vcpkgDirectory: '${{github.workspace}}/lib/vcpkg'
      
    - if: ${{ (matrix.os == 'ubuntu-latest') || (matrix.os == 'macos-latest') }}
      name: Install Qt (ubuntu-latest || macos-latest)
      uses: jurplel/install-qt-action@v3
      with:
          version: '6.5.1'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          set-env: 'true'
          
    - if: matrix.os == 'windows-latest'
      name: Install Qt (windows-latest)
      uses: jurplel/install-qt-action@v3
      with:
          version: '6.5.1'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          set-env: 'true'
          arch: 'win64_mingw'
      
    - name: Run CMake consuming CMakePresets.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'betacraft'
          buildPreset: 'betacraft'
          buildPresetAdditionalArgs: "['--config Release']"

    - name: Test
      working-directory: ${{github.workspace}}/build/betacraft
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
